version: '2'
services:
  person-cmd:
      image: node:6
      restart: always
      networks:
        - main

  user-cmd:
      image: node:6
      restart: always
      networks:
        - main

  tenant-cmd:
      image: node:6
      restart: always
      networks:
        - main

  pillar-cmd:
       image: node:6
       restart: always
       networks:
         - main

  content-cmd:
      image: node:6
      restart: always
      networks:
        - main

  saga-service:
      image: node:6
      restart: always
      networks:
        - main

  query-service:
    image: node:6
    restart: always
    networks:
      - main

  websocket-service:
    image: node:6
    restart: always
    networks:
      - main

  mongo:
    networks:
      - main
    image: mongo

  rabbit:
    networks:
      - main
    image: rabbitmq

  kong:
    restart: always
    image: mashape/kong
    networks:
      - main
    ports:
      - "8000:8000"

  kongfig:
    depends_on:
      - kong
    build:
      context: .
      dockerfile: ./kongfig_fix/kongfig.Dockerfile
    networks:
      - main

  kong-database:
    image: cassandra:2.2.1
    networks:
      - main

networks:
  main:
    driver: bridge
