version: '2'
services:

  kong:
    ports:
      - "8000:80"

  product-cmd:
    environment:
      - NODE_ENV production
    command: npm run start:production

  proposal-cmd:
    environment:
      - NODE_ENV production
    command: npm run start:production

  query-service:
    environment:
      - NODE_ENV production
    command: npm run start:production

  websocket-service:
    environment:
      - NODE_ENV production
    command: npm run start:production

  saga-service:
      environment:
        - NODE_ENV production
      command: npm run start:production
  person-cmd:
      environment:
        - NODE_ENV production
      command: npm run start:production
  user-cmd:
      environment:
        - NODE_ENV production
      command: npm run start:production
  tenant-cmd:
      environment:
        - NODE_ENV production
      command: npm run start:production

