version: '2'
services:
  kong:
    container_name: kong

  kongfig:
    container_name: kongfig

  kong-database:
    container_name: kong-db

  query-service:
    container_name: query-service
    environment:
      - NODE_ENV development
    volumes:
      - ./query-service:/app
    ports:
      - "8003:80"
    command: npm run start:dev
    working_dir: /app

  websocket-service:
    container_name: websocket-service
    environment:
      - NODE_ENV development
    volumes:
      - ./websocket-service:/app
    ports:
      - "8004:80"
    command: npm run start:dev
    working_dir: /app

  user-cmd:
    container_name: user-cmd
    environment:
      - NODE_ENV development
    volumes:
      - ./user-cmd-service:/app/src
    ports:
      - "8005:80"
    command: npm run start:dev
    working_dir: /app/src

  person-cmd:
    container_name: person-cmd
    environment:
      - NODE_ENV development
    volumes:
      - ./person-cmd-service:/app/src
    ports:
      - "8006:80"
    command: npm run start:dev
    working_dir: /app/src

  saga-service:
    container_name: saga-service
    links:
     - person-cmd
     - user-cmd
    environment:
      - NODE_ENV development
    volumes:
      - ./saga-service:/app/src
    ports:
      - "8007:80"
    command: npm run start:dev
    working_dir: /app/src

  tenant-cmd:
    container_name: tenant-cmd
    environment:
      - NODE_ENV development
    volumes:
      - ./tenant-cmd-service:/app/src
    ports:
      - "8008:80"
    command: npm run start:dev
    working_dir: /app/src

  pillar-cmd:
    container_name: pillar-cmd
    environment:
      - NODE_ENV development
    volumes:
      - ./pillar-cmd-service:/app/src
    ports:
      - "8009:80"
    command: npm run start:dev
    working_dir: /app/src

  content-cmd:
    container_name: content-cmd
    environment:
      - NODE_ENV development
    volumes:
      - ./content-cmd-service:/app/src
    ports:
      - "8010:80"
    command: npm run start:dev
    working_dir: /app/src

  mongo:
    container_name: mongo
    ports:
      - "27017:27017"
  rabbit:
    container_name: rabbit
    ports:
      - "5672:5672"
