version: '2'
services:

  kong:
    ports:
      - "8000:80"

  product-cmd:
    environment:
      - NODE_ENV production
    command: npm run start:prod

  proposal-cmd:
    environment:
      - NODE_ENV production
    command: npm run start:prod

  query-service:
    environment:
      - NODE_ENV production
    command: npm run start:prod

  websocket-service:
    environment:
      - NODE_ENV production
    command: npm run start:prod

  saga-service:
      environment:
        - NODE_ENV production
      command: npm run start:prod
  person-cmd:
      environment:
        - NODE_ENV production
      command: npm run start:prod
  user-cmd:
      environment:
        - NODE_ENV production
      command: npm run start:prod
  tenant-cmd:
      environment:
        - NODE_ENV production
      command: npm run start:prod
