---
root: true
env:
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 7
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
    experimentalObjectRestSpread: true
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  default-case:
    - error
  eqeqeq:
    - warn
    - always
  no-eval:
    - error
  no-fallthrough:
    - warn
  no-lone-blocks:
    - error
  no-loop-func:
    - error
  no-multi-spaces:
    - error
  no-multi-str:
    - error
  no-param-reassign:
    - error
  no-self-compare:
    - error
  no-useless-escape:
    - error
  no-useless-concat:
    - error
  no-with:
    - error
  yoda:
    - error
  no-unused-vars:
    - warn
  comma-spacing:
    - error
    -
      before: false
      after: true
  eol-last:
    - error
  arrow-spacing:
    - error
    -
      before: true
      after: true
  generator-star-spacing:
    - error
    -
      before: false
      after: true
  no-confusing-arrow:
    - error
    -
      allowParens: true
  no-duplicate-imports:
    - error
  no-var:
    - error
  object-shorthand:
    - error
  prefer-const:
    - error
  prefer-rest-params:
    - error
  prefer-spread:
    - error
  prefer-template:
    - error
  rest-spread-spacing:
    - error
    - never
  template-curly-spacing:
    - error
  yield-star-spacing:
    - error
    - after
  no-console:
    - warn
  no-mixed-spaces-and-tabs:
    - off
  indent:
    - off
  require-yield:
    - off
