---
apis:
  - name: proposal-cmd
    attributes:
      upstream_url: http://proposal-cmd/
      request_path: /proposal
      strip_request_path: true
  - name: product-cmd
    attributes:
      upstream_url: http://product-cmd/
      request_path: /product
      strip_request_path: true
  - name: query-service
    attributes:
      upstream_url: http://query-service/
      request_path: /graphql
      strip_request_path: true
  - name: person-cmd
    attributes:
      upstream_url: http://person-cmd/
      request_path: /person
      strip_request_path: true
  - name: user-cmd
    attributes:
      upstream_url: http://user-cmd/
      request_path: /user
      strip_request_path: true
  - name: tenant-cmd
    attributes:
      upstream_url: http://tenant-cmd/
      request_path: /tenant
      strip_request_path: true
  - name: pillar-cmd
    attributes:
      upstream_url: http://pillar-cmd/
      request_path: /pillar
      strip_request_path: true
  - name: content-cmd
    attributes:
      upstream_url: http://content-cmd/
      request_path: /content
      strip_request_path: true
  - name: saga-service
    attributes:
      upstream_url: http://saga-service/
      request_path: /saga
      strip_request_path: true
