---
resources:
  - name: culture-develop
    type: git
    source:
      uri: git@bitbucket.org:ultilabs/culture-shock-server.git
      branch: ci
      private_key: {{bitbucket-key}}
jobs:
  - name: test-communication
    plan:
      - get: culture-develop
        trigger: true

      - task: test
        file: culture-develop/communication-service/communication-test.yml

